FROM abernix/meteord:node-8-base

RUN apt-get upgrade -y && apt-get update

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
RUN echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.6 main" | tee /etc/apt/sources.list.d/mongodb-org-3.6.list
RUN apt-get update && apt-get install -y mongodb-org

RUN apt-get update && apt-get install -y \
    python3 \
    python3-numpy \
    python3-scipy \
    python3-pip

RUN pip3 install pymongo

RUN apt-get upgrade -y && apt-get update